FROM tomcat:8.5-jdk17-corretto
# ADD ./EasyShopReport/EasyShopReport.war /usr/local/tomcat/webapps/
ADD ./EasyShopReport/easyshop_rep.war /usr/local/tomcat/webapps/
EXPOSE 8080
CMD ["catalina.sh", "run"]